FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json ./

RUN yarn install --non-interactive

COPY . .

RUN yarn build

FROM nginx:1.27-alpine AS runner

ENV PORT=8080

COPY nginx.coolify.conf.template /etc/nginx/templates/default.conf.template
COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]
