// Shared types used across the monorepo

export enum UserType {
  ADMIN = 'admin',
  STUDENT = 'student',
}

export enum OrderStatus {
  PENDING = 'pending',
  APPROVED = 'approved',
  REJECTED = 'rejected',
  DELIVERED = 'delivered',
}

export enum ShipmentStatus {
  OPEN = 'open',
  COMPLETED = 'completed',
  CANCELLED = 'cancelled',
}

export enum MovementType {
  IN = 'in',
  OUT = 'out',
}

export enum MovementOrigin {
  SHIPMENT = 'shipment',
  ORDER = 'order',
}

export enum SizeType {
  NONE     = 'none',
  CLOTHING = 'clothing',
  SHOES    = 'shoes',
}

export enum StudentAid {
  AUXILIO_ALIMENTACAO        = 'Auxílio Alimentação (VC)',
  AUXILIO_TRANSPORTE_MUNICIPAL = 'Auxílio Transporte Municipal (VC)',
  AUXILIO_COPIA_IMPRESSAO    = 'Auxílio Cópia e Impressão (VC)',
  BOLSA_ESTUDO               = 'Bolsa de Estudo (VC)',
  AUXILIO_MORADIA            = 'Auxílio Moradia (VC)',
  AUXILIO_TRANSPORTE_INTERMUNICIPAL = 'Auxílio Transporte Intermunicipal (VC)',
}

export enum IntakeForm {
  SISU_AMPLA_CONCORRENCIA                     = 'SISU / AMPLA CONCORRÊNCIA',
  SISU_ESCOLAS_PUBLICAS                       = 'SISU / ESCOLAS PÚBLICAS',
  SISU_ESCOLAS_PUBLICAS_BAIXA_RENDA           = 'SISU / ESCOLAS PÚBLICAS / BAIXA RENDA',
  SISU_ESCOLAS_PUBLICAS_PPI                   = 'SISU / ESCOLAS PÚBLICAS / AUTODECLARAÇÃO - PRETOS, PARDOS E INDÍGENAS',
  SISU_ESCOLAS_PUBLICAS_BAIXA_RENDA_PPI       = 'SISU / ESCOLAS PÚBLICAS / BAIXA RENDA / AUTODECLARAÇÃO - PRETOS, PARDOS E INDÍGENAS',
  SISU_ESCOLAS_PUBLICAS_PPI_PCD               = 'SISU / ESCOLAS PÚBLICAS / AUTODECLARAÇÃO - PRETOS, PARDOS E INDÍGENAS / PESSOAS COM DEFICIÊNCIA',
  SISU_ESCOLAS_PUBLICAS_BAIXA_RENDA_PPI_PCD   = 'SISU / ESCOLAS PÚBLICAS / BAIXA RENDA / AUTODECLARAÇÃO - PRETOS, PARDOS E INDÍGENAS / PESSOAS COM DEFICIÊNCIA',
  PROCESSO_SELETIVO_AMPLA_CONCORRENCIA        = 'PROCESSO SELETIVO / AMPLA CONCORRÊNCIA',
  PROCESSO_SELETIVO_ESCOLAS_PUBLICAS          = 'PROCESSO SELETIVO / ESCOLAS PÚBLICAS',
  PROCESSO_SELETIVO_ESCOLAS_PUBLICAS_BAIXA_RENDA = 'PROCESSO SELETIVO / ESCOLAS PÚBLICAS / BAIXA RENDA',
  PROCESSO_SELETIVO_ESCOLAS_PUBLICAS_PPI      = 'PROCESSO SELETIVO / ESCOLAS PÚBLICAS / AUTODECLARAÇÃO - PRETOS, PARDOS E INDÍGENAS',
  PROCESSO_SELETIVO_ESCOLAS_PUBLICAS_BAIXA_RENDA_PPI = 'PROCESSO SELETIVO / ESCOLAS PÚBLICAS / BAIXA RENDA / AUTODECLARAÇÃO - PRETOS, PARDOS E INDÍGENAS',
  PROCESSO_SELETIVO_QUILOMBOLAS               = 'PROCESSO SELETIVO / QUILOMBOLAS',
  PROCESSO_SELETIVO_PCD                       = 'PROCESSO SELETIVO / PESSOA COM DEFICIÊNCIA',
  PROCESSO_SELETIVO_ESCOLAS_PUBLICAS_PCD      = 'PROCESSO SELETIVO / ESCOLAS PÚBLICAS / PESSOAS COM DEFICIÊNCIA',
  PROCESSO_SELETIVO_ESCOLAS_PUBLICAS_PCD_BAIXA_RENDA = 'PROCESSO SELETIVO / ESCOLAS PÚBLICAS / PESSOAS COM DEFICIÊNCIA / BAIXA RENDA',
  PROCESSO_SELETIVO_ESCOLAS_PUBLICAS_PCD_PPI  = 'PROCESSO SELETIVO / ESCOLAS PÚBLICAS / PESSOAS COM DEFICIÊNCIA / AUTODECLARAÇÃO - PRETOS, PARDOS E INDÍGENAS',
  PROCESSO_SELETIVO_ESCOLAS_PUBLICAS_PCD_BAIXA_RENDA_PPI = 'PROCESSO SELETIVO / ESCOLAS PÚBLICAS / PESSOAS COM DEFICIÊNCIA / BAIXA RENDA / AUTODECLARAÇÃO - PRETOS, PARDOS E INDÍGENAS',
  PROCESSO_SELETIVO_VAGAS_REMANESCENTES_PPI   = 'PROCESSO SELETIVO PARA VAGAS REMANESCENTES / ESCOLAS PÚBLICAS / AUTODECLARAÇÃO - PRETOS, PARDOS E INDÍGENAS',
  PROGRAMA_PEC_G                              = 'PROGRAMA PEC-G',
}

export enum EducationLevel {
  GRADUACAO = 'Graduação',
  MEDIO     = 'Médio',
}

export enum StudentModality {
  BACHARELADO          = 'Bacharelado',
  LICENCIATURA         = 'Licenciatura',
  TECNICO_INTEGRADO    = 'Técnico Integrado',
  TECNICO_SUBSEQUENTE  = 'Técnico Subsequente',
}

export const CLOTHING_SIZES = ['PP', 'P', 'M', 'G', 'GG', 'GGG'] as const;
export const SHOE_SIZES     = ['33','34','35','36','37','38','39','40','41','42','43','44','45'] as const;
export const NO_SIZE        = 'none' as const;

export interface JwtPayload {
  sub: number;       // user id
  email: string;
  userType: UserType;
  iat?: number;
  exp?: number;
}
